name: Create Branch from Issue
on:
  issues:
    types: [assigned]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set branch prefix
        id: set-prefix
        run: |
          prefix=i
          echo "prefix=${prefix:-issue}" >> $GITHUB_OUTPUT

      - name: Create branch from issue
        id: create-branch
        run: |
          title=$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g' | cut -c1-50 | sed 's/-*$//')
          branch="${{ steps.set-prefix.outputs.prefix }}${{ github.event.issue.number }}-${title:-issue}"
         
          git fetch --all --prune
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          if git ls-remote --heads origin "$branch" | grep -q "$branch"; then
            echo "Branch already exists, skipping creation"
          else
            git switch -c "$branch"
            git push -u origin "$branch"
          fi

          echo "branch-name=$branch" >> $GITHUB_OUTPUT
          
      - name: Comment on issue
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "🚀 Branch ready at \`${{ steps.create-branch.output.branch-name }}\`

          You can now work on this issue by checking out the branch:
          \`\`\`bash
          git fetch --all --prune
          git checkout ${{ steps.create-branch.outputs.branch-name }}
          \`\`\``"
        env:
          GH_TOKEN: ${{ github.token }}
