name: Create Branch from Issue
on:
  issues:
    types: [assigned]
jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Set branch prefix
          prefix=i

          # Create branch from issue
          title=$(echo "${{ github.event.issue.title }}" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g' | cut -c1-50 | sed 's/-*$//')
          branch="${prefix}${{ github.event.issue.number }}-${title:-issue}"
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git switch -c "$branch" && git push -u origin "$branch"
          
          # Comment on issue
          gh issue comment ${{ github.event.issue.number }} --body "🚀 Branch created: \`$branch\`

          You can now work on this issue by checking out the branch:
          \`\`\`bash
          git fetch origin
          git checkout ${{ steps.create-branch.outputs.branch-name }}
          \`\`\``"
        env:
          GH_TOKEN: ${{ github.token }}
